config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum role: [:user, :degustator, :organizator, :admin]

  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/main_controller.rb
class MainController < ApplicationController
    def index
        
        #flash.now[:notice] = "Logged in succesfully"
        #flash.now[:alert]  = "Invalid e-mail or password"
        
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController

    def new
    end

    def create
        @user = User.find_by(email: params[:email])

        if @user.present?
            # Send email
            PasswordMailer.with(user: @user).reset.deliver_now
        end


        redirect_to root_path, notice: "If that account with email was found, we have sent an email for password reset"
    end

    def edit
        @user = User.find_signed!(params[:token], purpose: "password_reset")
    rescue  ActiveSupport::MessageVerifier::InvalidSignature
        redirect_to sign_in_path, alert: "Your token has expired. Please try again" 
    end

    def update
        @user = User.find_signed!(params[:token], purpose: "password_reset")
        if @user.update(password_params)
           redirect_to sign_in_path, notice: "Your password was reset successfully. Please sign in"
        else 
           render :edit
        end
    end

    def password_params
       params.require(:user).permit(:password, :password_confirmation)  
    end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController

before_action :require_user_logged_in!

    def edit
    end

    def update
        if Current.user.update(password_params)
            redirect_to root_path, notice: "Password successfully changed"
        else
          render :edit
        end
    end

    private

    def password_params
        params.require(:user).permit(:password, :password_confirmation)
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
           # user id based on session, saved in DB
           session[:user_id] = @user.id
           # redirect to man page with notice
           redirect_to root_path, notice: "Successfully created account"
        else
           
           render :new    
       end

    end

    private

    def user_params
        # secure way to send params and only this params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
    end

    def create
        user = User.find_by(email: params[:email])

        if user.present? && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to root_path, notice: "Logged in succesfully"
        else
            flash[:alert] = "Invalid email or password"
            render :new
        end
    end
    
    def destroy
        session[:user_id] = nil
        redirect_to root_path, notice: "Logged out"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/about/index.html.erb
<h1>About Us</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WineappV1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/main/index.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1>Welcome</h1>
</div>

app/views/pages/home.html.erb
<h1>Welcome</h1>
<p>Find me in app/views/pages/home.html.erb</p>

<% if current_user %>
    <p> Vitaj späť, <%= current_user.email %>!</p>
    <p> Si úspešne prihlásený ako [<%= current_user.role %>]</p>

    <% if current_user.admin?%>
    <br>
        Je registrovaných <%= User.count %> používateľov.
    <br>
    <% end %>
    
    <br>
    <%= link_to "Odhlásenie", destroy_user_session_path, 'data-turbo-method': :delete %>

<% else %>
    <p> Nie si prihlásený!</p>
    <%= link_to "Registrácia", new_user_registration_path %>
    <%= link_to "Prihlásenie", new_user_session_path %>

<% end %>

app/views/password_resets/edit.html.erb
<h1>Reset your password</h1>

<%= form_with model: @user, local: true, url: password_reset_edit_path(token: params[:token]) do |form| %>
    <!-- # errors pre usera, treba mat specifikovany model -->
    <% if form.object.errors.any? %>
        <div class="alert alert-danger">
            <% form.object.errors.full_messages.each do |message|%>
                <div><%= message %></div>
            <% end %>
        </div>
    <% end %>


    <div class="mb-3">
        <%= form.label :password %>
        <%= form.password_field :password, class: "form-control", placeholder: "heslo"%>
    </div>

    <div class="mb-3">
        <%= form.label :password_confirmation %>
        <%= form.password_field :password_confirmation, class: "form-control", placeholder: "zopakuj heslo"%>
    </div>

<div class="mb-3">
        <%= form.submit "Password reset", class: "btn btn-primary" %>
</div>


<% end %>

app/views/password_resets/new.html.erb
<h1>Forgot password</h1>

<%= form_with local: true, url: password_reset_path do |form| %>

<div class="mb-3">
        <%= form.label :email %>
        <%= form.text_field :email, class: "form-control", placeholder: "mojemail@domena.com" %>
</div>

<div class="mb-3">
        <%= form.submit "Password reset", class: "btn btn-primary" %>
</div>


<% end %>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
    <div class="alert alert-info mt-4" role="alert">
        <%= flash[:notice] %>
    </div>
<% end %>

<% if flash[:alert] %>
    <div class="alert alert-warning mt-4" role="alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container-fluid">
    <%= link_to "Navbar", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
          
        </li>
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
          
        </li>
 
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown link
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>

      <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <% if Current.user %>
        <li class="nav-item">
         <%= link_to Current.user.email, edit_password_path, class: "nav-link" %>
        </li>
        <li class="nav-item">  
          <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-secondary" %>
        </li>

        <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
        </li>
        <li class="nav-item">  
          <%= link_to "Login", sign_in_path, class: "nav-link" %>
        </li>
        <% end %>
      </ul>

    </div>
  </div>
</nav>